# Generated by Django 4.1.4 on 2023-02-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1600, null=True, verbose_name='Описание')),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='adverts/img/', verbose_name='Фотография')),
                ('book_condition', models.CharField(choices=[('NEW', 'Новое'), ('EXCELLENT', 'Отличное'), ('GOOD', 'Хорошее'), ('AVERAGE', 'Среднее')], max_length=50, verbose_name='Состояние')),
                ('deal_type', models.CharField(choices=[('PERSONAL', 'Личная встреча'), ('PICKUP_POINT', 'Доставка в отделение или пункт выдачи'), ('COURIER', 'Курьерская доставка')], max_length=50, verbose_name='Тип сделки')),
                ('deal_terms', models.TextField(max_length=600, verbose_name='Условия сделки')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('bio', models.TextField(max_length=1600, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1600, null=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/img/', verbose_name='Обложка')),
                ('isbn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уникальный номер (ISBN)')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Число страниц')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BookCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название произведения', max_length=255, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, help_text='О чем эта книга?', max_length=1000, null=True, verbose_name='Описание книги')),
                ('image', models.ImageField(blank=True, help_text='Приложите фотографию книги', null=True, upload_to='book_cover/', verbose_name='Фотография книги')),
                ('isbn', models.CharField(blank=True, help_text='ISBN - это уникальный индентификатор книги. Он може быть указан на первой странице или с обратной стороны книги.', max_length=100, null=True, verbose_name='International Standard Book Number')),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'Новое'), ('EXCELLENT', 'Отличное'), ('GOOD', 'Хорошее'), ('AVERAGE', 'Среднее')], help_text='Выберите из списка состояние данного экземпляра.', max_length=50, null=True, verbose_name='Состояние книги')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Карточка книги',
                'verbose_name_plural': 'Карточки книг',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='books.bookcard', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
    ]
