# Generated by Django 2.2.16 on 2022-12-15 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(verbose_name='Date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(choices=[('Роман', 'Роман'), ('Драма', 'Драма'), ('Проза', 'Проза'), ('Детектив', 'Детектив'), ('Фантастика', 'Фантастика')], max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField(default='Отсутствует..', max_length=1000, verbose_name='Описание жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('description', models.TextField(max_length=1000, verbose_name='Кратко о книге')),
                ('isbn', models.CharField(help_text='ISBN это уникальный индентификатор книги.', max_length=100, verbose_name='International Standard Book Number')),
                ('condition', models.CharField(choices=[('Новый/(ая)', 'Новый/(ая)'), ('Как новый/(ая)', 'Как новый/(ая)'), ('Очень хорошее', 'Очень хорошее'), ('Достойное', 'Достойное'), ('Приемлемое', 'Приемлемое'), ('Практически приемлемое', 'Практически приемлемое')], default='Укажите состояние книги', max_length=120, verbose_name='Состояние книги')),
                ('creation_date', models.DateField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации книги на платформе.')),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='books.BookAuthor')),
                ('gentre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='genres', to='books.Genre')),
                ('pub_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
