# Generated by Django 2.2.16 on 2022-12-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='lang_id',
            field=models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('DE', 'Deutch')], default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='father_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='first_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='last_name',
            field=models.CharField(max_length=80),
        ),
    ]
