# Generated by Django 2.2.16 on 2022-12-26 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20221216_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lang_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.BookAuthor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='gentre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='books.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
