# Generated by Django 3.2 on 2023-01-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='book',
            new_name='book_card',
        ),
    ]
