# Generated by Django 2.2.16 on 2022-12-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20221226_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='gentre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Genre'),
        ),
    ]
